package lunartools.sqlrepeatabler.common.model;

public enum SimpleEvents {
	EXIT,
	MODEL_SQLINPUTFILESCHANGED,
	MODEL_INPUTSQLSCRIPTCHANGED,
	MODEL_CONVERTEDSQLSCRIPTCHANGED,
	MODEL_RESET,
	MODEL_CLEARINPUTPANEL,
	MODEL_FILEPROCESSINGORDERCHANGED,
	MODEL_SETTING_BACKGROUNDCOLOR_CHANGED,
	THEMEMANAGER_THEME_CHANGED;
}
