package lunartools.sqlrepeatabler;

public enum SimpleEvents {
	EXIT,
	MODEL_SQLINPUTFILESCHANGED,
	MODEL_INPUTSQLSCRIPTCHANGED,
	MODEL_CONVERTEDSQLSCRIPTCHANGED,
	MODEL_RESET,
	MODEL_CLEARINPUTPANEL,
	MODEL_FILEPROCESSINGORDERCHANGED;
}
