IF COL_LENGTH ('table_name','COLUMN1_NAME') IS NULL
BEGIN
    ALTER TABLE [table_name]
        ADD [COLUMN1_NAME] INT NULL;
END;

IF COL_LENGTH ('table_name','COLUMN2_NAME') IS NULL
BEGIN
    ALTER TABLE [table_name]
        ADD [COLUMN2_NAME] NVARCHAR(100) NULL;
END;

IF COL_LENGTH ('table_name','COLUMN3_NAME') IS NULL
BEGIN
    ALTER TABLE [table_name]
        ADD [COLUMN3_NAME] DATETIME NULL;
END;
